const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];
const machine=$('#machine'),statusEl=$('#status'),creditEl=$('#credit'),logEl=$('#eventLog'),bet=$('#bet'),start=$('#start'),stops=$$('.stop'),flowers=$$('.flower');
const state={version:'0.1.0',credit:50,bet:false,phase:'idle',stopIndex:0,scene:null,lamp:false,locks:[false,false,false],audio:null,master:null,fps:0};
function log(a,b=''){const t=new Date().toTimeString().slice(0,8);logEl.textContent=(logEl.textContent+`${t}  ${a}${b?'  '+b:''}\n`).split('\n').slice(-22).join('\n');}
function phase(p,label){state.phase=p;machine.dataset.phase=p;if(label)statusEl.textContent=label;log('PHASE',p)}
async function unlock(){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;if(!state.audio){state.audio=new AC();state.master=state.audio.createGain();state.master.gain.value=.12;state.master.connect(state.audio.destination)}if(state.audio.state==='suspended')await state.audio.resume()}
function tone(f,d=.05,v=.18){if(!state.audio||state.audio.state!=='running')return;const o=state.audio.createOscillator(),g=state.audio.createGain(),n=state.audio.currentTime;o.type='triangle';o.frequency.value=f;g.gain.setValueAtTime(v,n);g.gain.exponentialRampToValueAtTime(.0001,n+d);o.connect(g);g.connect(state.master);o.start();o.stop(n+d+.02)}
const symbols=['遊','果','鈴','星','BAR','遊','果','星','鈴','BAR','遊','鈴'];
class YuyuScene extends Phaser.Scene{
 constructor(){super('yuyu');this.reels=[]}
 create(){state.scene=this;this.cameras.main.setBackgroundColor('#eee9df');this.add.rectangle(171,88,342,176,0xe9e4d9);for(let i=0;i<3;i++)this.makeReel(i);[52,88,124].forEach(y=>this.add.rectangle(171,y,330,1,0x8c786b,.22).setDepth(20));this.add.rectangle(171,88,334,170,0xffffff,0).setStrokeStyle(2,0x3b3032,.8).setDepth(30);log('SCENE','READY')}
 makeReel(i){const x=58+i*113,r={x,offset:i*72,speed:0,spinning:false,locked:false,cells:[]};this.add.rectangle(x,88,102,166,0xf9f5e9).setStrokeStyle(1,0xb7aa98).setDepth(1);for(let j=0;j<7;j++){const plate=this.add.rectangle(x,0,90,33,0xfffcf1).setStrokeStyle(1,0xd9d0c0).setDepth(4),label=this.add.text(x,0,'',{fontFamily:'Georgia,serif',fontStyle:'900',fontSize:'22px',color:'#5a173f'}).setOrigin(.5).setDepth(5);r.cells.push({plate,label,j})}this.reels.push(r);this.paint(r)}
 paint(r){r.cells.forEach((c,k)=>{let n=Math.round(r.offset/36)+k-3;let y=88+(k-3)*36-(r.offset%36);while(y<-20)y+=252;while(y>196)y-=252;const idx=((n%symbols.length)+symbols.length)%symbols.length;c.plate.y=y;c.label.y=y;c.label.setText(symbols[idx]);const visible=y>=19&&y<=157;c.plate.setVisible(visible);c.label.setVisible(visible).setAlpha(r.spinning?.70:1);c.plate.setAlpha(r.spinning?.78:1)})}
 begin(){this.reels.forEach((r,i)=>{r.spinning=true;r.locked=false;r.speed=11+i*.45});state.locks=[false,false,false];log('REEL','SPIN')}
 stopReel(i){const r=this.reels[i];r.spinning=false;r.speed=0;r.offset=Math.round(r.offset/36)*36;r.locked=true;this.paint(r);state.locks[i]=true;log('REEL_ALIGN',`R${i+1}`);log('LOCK',String(i+1))}
 update(){this.reels.forEach(r=>{if(r.spinning){r.offset=(r.offset+r.speed)%432;this.paint(r)}});const now=performance.now();if(!this.last){this.last=now;return}const fps=1000/(now-this.last);this.last=now;state.fps=state.fps*.9+fps*.1;$('#fps').textContent=`${Math.round(state.fps)} FPS`}
}
new Phaser.Game({type:Phaser.WEBGL,width:342,height:176,parent:'game',transparent:false,scene:YuyuScene,render:{antialias:true,pixelArt:false},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH}});
bet.addEventListener('click',async()=>{await unlock();if(state.phase!=='idle')return;state.bet=true;state.credit--;creditEl.textContent=`CREDIT ${state.credit}`;start.disabled=false;tone(720);phase('bet','STARTできます');log('BET','1')});
start.addEventListener('click',async()=>{await unlock();if(!state.bet)return;state.stopIndex=0;start.disabled=true;stops.forEach(b=>b.disabled=false);state.scene.begin();tone(110,.12,.14);phase('spin','REELS SPINNING');log('GAME_EVENT','LEVER_ON')});
stops.forEach((b,i)=>b.addEventListener('click',async()=>{await unlock();if(i!==state.stopIndex||state.phase!=='spin')return;b.disabled=true;state.scene.stopReel(i);tone(190+i*35,.06,.2);state.stopIndex++;log('GAME_EVENT',`STOP_${i+1}`);if(state.stopIndex===3){stops.forEach(x=>x.disabled=true);phase('judge','……');setTimeout(()=>{state.lamp=true;flowers.forEach(f=>f.classList.add('on'));phase('bonus','BONUS');tone(523,.18,.17);setTimeout(()=>tone(659,.22,.14),70);log('YUYU','FLOWER_LAMP_ON');log('GAME_EVENT','BONUS_ENTER')},360)}}));
window.__YUYU_STATE__=()=>({version:state.version,phase:state.phase,credit:state.credit,lamp:state.lamp,locks:[...state.locks],audio:{hasContext:!!state.audio,contextState:state.audio?.state||'none'},reels:state.scene?.reels.map((r,i)=>({index:i+1,offset:r.offset,latticeError:Math.abs(r.offset-Math.round(r.offset/36)*36),locked:r.locked}))||[]});
window.__YUYU_RESET__=()=>{state.bet=false;state.stopIndex=0;state.lamp=false;flowers.forEach(f=>f.classList.remove('on'));stops.forEach(x=>x.disabled=true);start.disabled=true;phase('idle','BETしてください')};