const { test, expect } = require('@playwright/test');
const fs=require('fs'),path=require('path'); const evidenceDir=path.join(__dirname,'evidence'); const targetPath='/research/nextgen_pachislot_expression_lab/index.html';
async function shot(p,n){await p.screenshot({path:path.join(evidenceDir,`${n}.png`),fullPage:true});}
async function waitEvent(p,t){await expect.poll(async()=>p.locator('#eventLog').textContent(),{timeout:5000}).toContain(t);}
async function reel(p){return p.evaluate(()=>window.__REEL_LINE_STATE__?.()||null);} async function light(p){return p.evaluate(()=>window.__REEL_LIGHT_STATE__?.()||null);} async function yuyu(p){return p.evaluate(()=>window.__YUYU_STATE__?.()||null);} async function audio(p){return p.evaluate(()=>window.__NEXTGEN_AUDIO_STATE__?.()||null);}

test('YUYU v0.1 full 1G iPhone benchmark',async({page})=>{
 fs.mkdirSync(evidenceDir,{recursive:true}); const base=process.env.PLAYTEST_BASE_URL||'http://127.0.0.1:4173'; const url=new URL(targetPath,base).toString(); const consoleMessages=[],pageErrors=[]; page.on('console',m=>consoleMessages.push(`[${m.type()}] ${m.text()}`)); page.on('pageerror',e=>pageErrors.push(String(e)));
 await page.goto(url,{waitUntil:'networkidle'}); await expect(page.locator('#machine')).toBeVisible(); await expect(page.locator('.lab-head b')).toContainText('遊遊'); await expect(page.locator('.lab-head small')).toContainText('YUYU v0.1.0'); await expect.poll(async()=>page.evaluate(()=>typeof window.__YUYU_STATE__)).toBe('function'); await waitEvent(page,'SCENE  READY'); await page.waitForTimeout(300);
 let ys=await yuyu(page); expect(ys.version).toBe('0.1.0'); expect(ys.lamp).toBe(false); expect(ys.reel.lineCount).toBe(3); expect(ys.light.topCurveAlpha.every(v=>v===0)).toBe(true); expect(ys.light.bottomCurveAlpha.every(v=>v===0)).toBe(true); await shot(page,'00-yuyu-idle');
 await page.locator('#bet').tap(); await expect(page.locator('#status')).toContainText('START'); await shot(page,'01-yuyu-bet'); await page.locator('#start').tap(); await expect(page.locator('#status')).toContainText(/REELS/); await page.waitForTimeout(260); await shot(page,'02-yuyu-cruise');
 for(let i=0;i<3;i++){const s=page.locator('.stop').nth(i); await expect(s).toBeEnabled(); await s.tap(); await waitEvent(page,`LOCK_${i+1}`); await waitEvent(page,`REEL_ALIGN  R${i+1}`); const rs=await reel(page); expect(rs.reels[i].mode).toBe('locked'); expect(rs.reels[i].latticeError).toBeLessThanOrEqual(.001); expect(rs.reels[i].lineErrors.every(v=>v!==null&&v<=.001)).toBe(true); await shot(page,`0${i+3}-yuyu-stop${i+1}`);}
 await expect(page.locator('#machine')).toHaveAttribute('data-phase',/judge|bonus|idle/,{timeout:5000}); await page.waitForTimeout(750); ys=await yuyu(page); const as=await audio(page); await shot(page,'06-yuyu-bonus');
 expect(ys.lamp).toBe(true); expect(ys.bonusSignals).toBeGreaterThanOrEqual(1); expect(as.enabled).toBe(true); expect(as.contextState).toBe('running'); const report=await page.evaluate(()=>({status:document.querySelector('#status')?.textContent,phase:document.querySelector('#machine')?.dataset.phase,eventLog:document.querySelector('#eventLog')?.textContent,yuyu:window.__YUYU_STATE__?.(),baseline:window.__PHASER_BASELINE_STATE__?.(),fps:document.querySelector('#fps')?.textContent})); fs.writeFileSync(path.join(evidenceDir,'yuyu-v010-report.json'),JSON.stringify({url,report,consoleMessages,pageErrors},null,2)); expect(report.eventLog).toContain('YUYU  CHANCE_LAMP_ON'); expect(report.eventLog).toContain('BONUS'); expect(consoleMessages.filter(x=>x.includes('setMask')&&x.includes('not supported in WebGL'))).toEqual([]); expect(pageErrors).toEqual([]);
});
