const { test, expect } = require('@playwright/test');
const fs=require('fs'),path=require('path');const evidenceDir=path.join(__dirname,'evidence-yuyu');const targetPath='/research/yuyu_normal_type_lab/index.html?v=048';
async function shot(page,name){await page.screenshot({path:path.join(evidenceDir,`${name}.png`),fullPage:true});}
async function waitLog(page,text){await expect.poll(async()=>page.locator('#eventLog').textContent(),{timeout:5000}).toContain(text);}
async function state(page){return page.evaluate(()=>window.__YUYU_STATE__?.()||null);}
test('YUYU v0.4.8 permanent 2.5D printed symbol Mesh2D + full 1G iPhone playtest',async({page})=>{
 fs.mkdirSync(evidenceDir,{recursive:true});const base=process.env.PLAYTEST_BASE_URL||'http://127.0.0.1:4173';const url=new URL(targetPath,base).toString();const consoleMessages=[],pageErrors=[];
 page.on('console',m=>consoleMessages.push(`[${m.type()}] ${m.text()}`));page.on('pageerror',e=>pageErrors.push(String(e)));
 await page.goto(url,{waitUntil:'networkidle'});await expect(page.locator('#machine')).toBeVisible();await expect(page.locator('header small')).toContainText('YUYU v0.4.8');
 await waitLog(page,'PATCH  DEPTH25D_V0_4_7');await waitLog(page,'PATCH  SYMBOL_MESH_V0_4_8');await waitLog(page,'SYMBOL_SURFACE  MESH2D_PRINTED_SYMBOL_FILM');await waitLog(page,'SYMBOL_MESHES  21');await waitLog(page,'REFERENCE_COMPARE  HANAHANA_CLASS_NORMAL_TYPE');
 await page.waitForTimeout(350);let s=await state(page);
 expect(s.version).toBe('0.4.8');expect(s.phaser.renderer).toBe(2);expect(String(s.phaser.version)).toContain('4.2.1');expect(s.phaser.reelDirection).toBe('TOP_TO_BOTTOM');expect(s.phaser.motionProfile).toBe('ACCEL_CRUISE_BRAKE_SETTLE');expect(s.phaser.depthMode).toBe('PERMANENT_2_5D_REEL_STACK');
 expect(s.symbolMesh.mode).toBe('PERMANENT_SYMBOL_MESH_2_5D');expect(s.symbolMesh.enabled).toBe(true);expect(s.symbolMesh.comparisonMode).toBe(false);expect(s.symbolMesh.symbolMeshes).toBe(21);expect(s.symbolMesh.grid).toBe('5X3');expect(s.symbolMesh.vertexCountPerSymbol).toBe(15);expect(s.symbolMesh.triangleCountPerSymbol).toBe(16);expect(s.symbolMesh.orderedIndices).toBe(true);expect(s.symbolMesh.curvedSymbols).toBe(true);expect(s.symbolMesh.errors).toEqual([]);
 await shot(page,'00-idle-symbol-mesh');await page.locator('#bet').tap();await shot(page,'01-bet-symbol-mesh');await page.locator('#start').tap();await expect(page.locator('#status')).toContainText('REELS SPINNING');await waitLog(page,'REEL_SPEED  LAUNCH:84');
 const launch=await state(page),speed0=launch.reels.map(r=>r.speed),p0=launch.reels.map(r=>r.probeY);await page.waitForTimeout(70);const accel=await state(page),speed1=accel.reels.map(r=>r.speed),p1=accel.reels.map(r=>r.probeY);expect(speed1.every((v,i)=>v>speed0[i])).toBe(true);expect(p1.every((v,i)=>v>p0[i]+3)).toBe(true);await shot(page,'02a-accelerating-symbol-mesh');
 await waitLog(page,'REEL_SPEED  CRUISE_R1:520');await waitLog(page,'REEL_SPEED  CRUISE_R2:538');await waitLog(page,'REEL_SPEED  CRUISE_R3:556');const cruise=await state(page);expect(cruise.reels.every(r=>r.stage==='cruise')).toBe(true);await shot(page,'02b-cruise-symbol-mesh');
 const brakeEvidence=[];for(let i=0;i<3;i++){const before=await state(page),beforeSpeed=before.reels[i].speed;await page.locator('.stop').nth(i).tap();await waitLog(page,`REEL_BRAKE  R${i+1}:`);await page.waitForTimeout(55);const mid=await state(page);expect(mid.reels[i].speed).toBeLessThan(beforeSpeed);await waitLog(page,`REEL_SETTLE  R${i+1}->`);await waitLog(page,`LOCK  ${i+1}`);s=await state(page);expect(s.reels[i].locked).toBe(true);expect(s.reels[i].latticeError).toBeLessThanOrEqual(.001);brakeEvidence.push({beforeSpeed,midSpeed:mid.reels[i].speed,lockedTravel:s.reels[i].travel});await shot(page,`0${i+4}-stop${i+1}-symbol-mesh`);}
 await expect(page.locator('#machine')).toHaveAttribute('data-phase','bonus',{timeout:3000});await waitLog(page,'PHASER_FX  BONUS_BURST');await waitLog(page,'YUYU  FLOWER_LAMP_ON');await page.waitForTimeout(300);s=await state(page);expect(s.lamp).toBe(true);expect(s.locks.every(Boolean)).toBe(true);expect(s.audio.hasContext).toBe(true);expect(s.audio.contextState).toBe('running');await expect(page.locator('.flower.on')).toHaveCount(2);await shot(page,'07-bonus-lamps-symbol-mesh');
 fs.writeFileSync(path.join(evidenceDir,'yuyu-report.json'),JSON.stringify({url,state:s,symbolMesh:s.symbolMesh,depth25d:s.depth25d,reference:s.reference,optics:s.optics,film:s.film,acrylic:s.acrylic,motion:{speed0,speed1,p0,p1,brakeEvidence},consoleMessages,pageErrors,eventLog:await page.locator('#eventLog').textContent()},null,2));
 expect(pageErrors).toEqual([]);expect(consoleMessages.filter(x=>/error|exception/i.test(x))).toEqual([]);
});